### ISSUE TITLE
Godot randomly freezes after addon's installation

### ISSUE THREAD

**Issue by 0-Vanes-0** [ramokz/phantom-camera#405]
### Issue description

`Godot's version: v4.3.stable.steam [77dcf97d8]`
`OS: Windows 10`
`Addon version: 0.7.3`

Enabled addon "Phantom Camera" freezes Godot editor during trivia scene editing.
Each freeze leads to closing the editor and relaunching _(with hope)_.
I witnessed freezes after:
- addon installation
- adding node
- changing some parameter of addon's node or of built-in one

If I turn off the plugin in `Project Settings`, nothing freezes anymore.
In my `user://` folder (AppData/Roaming/Godot/<project_name>) there's no any log file which could clarify what happened.

### Steps to reproduce

1. Create new project
2. Install addon through "AssetLib"
3. Create a 3D scene
4. Try to add new nodes, either addon's ones or Godot's / change some node's parameters in Inspector tab

### (Optional) Minimal reproduction project

Here's link with my recording of catching this bug:
https://drive.google.com/file/d/18gU0pfRsrjh7iOF_vcoCCPmvKaHR4Kuu/view?usp=sharing

**Comment by 0-Vanes-0** [comment]
If possible, I'd like to get some help with investigation. Much time ago there was an output console on Godot's start, and as for now I didn't find how to get it back. It could have some info about the freezes of the editor.
My issue seems critical but it's hard to say what could be a problem here.

**Comment by ramokz** [comment]
That's very odd.

I can't say why that is happening, and have never come across anyone or myself experiencing this. So it seems like it might be a unique issue.

Have you tried either of the following:
1. Notice that you're launching Godot through Steam, so does the issue also occur if you download Godot from their website and launch that executable?
2. Does the issue also occur with other addons?
3. Have you tried on other machines?

**Comment by 0-Vanes-0** [comment]
Things seem weird.
1. Does launching from executable help? ~~Yes, no freezes.~~ No, caught it.
2. Other addons? No.
3. And the most odd thing: when I try Steam version on other PC - no freezes too.

I'm quite confused. 
My graphics drivers are up to date. 
In Steam inside Properties > Betas I've chosen "None", so it is 4.3 for sure.
I assume, there must be something wrong with my PC.
Reinstallation didn't help too.

**Comment by ramokz** [comment]
Given it sounds like it's running fine on another machine, it sounds like a machine-specific issue. Am not sure if I can realistically help debug that without either being able to replicate the issue or have any error outputs to work out from, unfortunately.

It might be a particular line in the addon, but, again, have no idea where to even start.

**Comment by 0-Vanes-0** [comment]
It's ok. I'll try to investigate it further. I will notify if the issue would be (somehow) fixed on new version of Phantom Camera.

**Comment by maxfoxino** [comment]
I can also confirm this issue, I was wondering what was causing my Godot to 'stop responding' after interacting with the **context menu in the Scene panel specifically**.
After experimenting with a project with and without Phantom Camera, I can safely say it is PA causing this issue.
Using Win11 24H2, Godot 4.3 on Steam, PA version 0.8.2.3 (Latest).
This issue appears to be _some sort_ of hardware issue, the freeze only occurs on my laptop and not my main Windows 10 PC.
Seeing that another user experiences this bug, is there anything I can do to help the investigation?

**Comment by ramokz** [comment]
We can try and narrow down the issue. Sounds like the addon might be triggering something that Godot doesn't like on some hardware. It's possible that it can be alleviated in the addon, and fixed upstream in Godot itself so it doesn't happen on any hardware.

Can start by finding common denominators.

- What hardware (CPU, GPU etc.) does your laptop have, and what does your main PC have?
- Are you running in `Forward+`, `Compatability` or `Mobile` mode (top-right corner of the Godot window)?

**Comment by 0-Vanes-0** [comment]
As for me, I had this issue with every rendering mode.
Speaking of my hardware:

- Laptop with the issue:
    - **Intel Core i5 12500H** (with Iris XE Graphics, that I don't use)
    - **Nvidia RTX 3050 Ti Laptop**
    - 16 GB RAM
    - Using SSD
- The other PC without the issue:
    - **Intel Core i5 10600**
    - **Nvidia GTX 1060 Ti**
    - 32 GB RAM
    - Using SSD as well

I suppose it could be something related to _"more fresh, newer"_ hardware..?
@maxfoxino , what about your setup?

**Comment by maxfoxino** [comment]
Hey, sorry for the late reply.
After a tiny bit more experimenting, reproduction seems quite inconsistent, with various different things (mostly) related to the Scene panel causing the 'not responding' window. I can also confirm this issue occurs on all rendering modes.
I have reproduced this bug _most consistently_ by:

- Renaming a Node (via double clicking its name or the context menu if I can activate it) , Rename display appears and then Godot immediately stops responding.
- Attempting to open the context menu (via right-clicking on a Node), Context menu does not open and Godot immediately stops responding.
- Hovering over Nodes in the Scene panel, the Node's tooltip displays and then Godot immediately stops responding.

Judging by these three triggers, I am assuming this crash has _something to do with_ the way PA interacts with Godot's Tooltip or Popup Window rendering? All these actions involve Tooltips or Popup Windows, almost exclusively in the Scene panel, but I _have_ had some stray crashes when hovering over elements of the toolbar and viewing their tooltips.

As for specs,

- Laptop (experiences the bug)
    - Intel Core i7-12700H 2.3GHz
    - NVIDIA RTX 4060 Laptop
    - 16 GB RAM
    - Using an SSD
- PC (does not experience the bug)
    - Intel Core i7-11700KF 3.6 GHz
    - NVIDIA RTX 3060Ti
    - 32 GB RAM
    - Using an SSD

**Comment by ramokz** [comment]
Thanks for sharing the specs!

It's a small sample size, but, so far appears to be exclusive to Nvidia GPUs and Intel CPUs. Both computers with the issue also have 16 GB of ram, but I very much doubt that has anything to do with it.

A couple of things to try:

---

## 1
Does the issue also occur in [Godot 4.4 rc1](https://godotengine.org/article/release-candidate-godot-4-4-rc-1/#downloads) that was released yesterday? Mainly to see if something in the latest Godot version that could have changed anything. It would also help verify that it isn't a Steam executable specific bug, though I think that's farfetched.

---

## 2

Are you using the latest Nvidia GPU drivers on all devices? Given the issue appears to be exclusive to Nvidia GPUs and that both the 30 and 40 series trigger the issue, I wonder if there's something specific within the addon's code, and / or Godot, that relies on a specific driver version.

---

## 3

I forgot to ask about this earlier, but does the issue occur if any of the addon nodes are in the scene tree, or only once the `PhantomCamera2D/3D` and `PhantomCameraHost` are added? Might help narrow down which file is causing the issue.

### If `PhantomCamera2D/3D` triggers the issue

If you dig into the addon's code for `phantom_camera_2d.gd` / `phantom_camera_3d.gd`, depending on the scene type you're working in, and remove (or comment out) the entire `func _validate_property(property: Dictionary) -> void:` function. It changes the inspector panel based on conditions, and so it could have something to do with it.

### If `PhantomCameraHost` triggers the issue
If you dig into  `phantom_camera_host.gd` and remove (or comment out) the entire `func _get_configuration_warnings() -> PackedStringArray:` function.

This is the only function that I can think of that should have any effect on the scene tree hierarchy / context menu.

---

## 4

If none of the above changes anything, we should dig into what @lord-muad-dib suggested earlier by running Godot from console and see if there's any output logs to be found there. Have a hunch it might get overly technical for what a GDScript addon can resolve, but it can point us in the right direction.

**Comment by maxfoxino** [comment]
Woah!
Great news, it appears the issue no longer occurs for me in Godot 4.4 RC-1! I was tinkering around with what I usually do to trigger it, drying various different combinations, and the freeze never occurred! After switching back to 4.3 Stable it started occurring again.
I guess this issue is an engine-specific rendering problem that PA just brings to light, and was fixed in 4.4?
Obviously, we cant say for sure this is fixed until 4.4 is released, and I will keep experimenting on the RC to try and reproduce it, but this is great news so far!
@0-Vanes-0 , try out the RC, does the issue appear to be fixed for you as well? Its possible I didn't test long enough.

**Comment by pikuler** [comment]
Thought I would just post an extra follow up here,
I have not experienced this issue on Godot 4.4 or 4.4.1, on any version of PA.
The issue has been completely resolved for me, it was most likely a PA-induced engine bug with my laptop hardware that got fixed in 4.4.

**Comment by ramokz** [comment]
Thanks for following up on this!
Gonna mark the issue as resolved, given there has been no further updates about the issue still occurring.

If it does resurface, do share!

**Comment by 0-Vanes-0** [comment]
Sorry for such delay _(started a new 3D project and returned to this issue)_, after hours and hours I've investigated some things.
### Short summary of facts
- This issue occurs only with my laptop while other PCs doesn't have any problems with the addon.
  - My CPU and GPU are `Intel Core i5 12500H` and `Nvidia RTX 3050 Ti Laptop`
  - The other PC (that doesn't have the issue) has `Intel Core i5 10600` and `Nvidia GTX 1660 Ti`
- Drivers are up-to-date, as well as Vulkan: 1.4.303
- Godot version: 4.4.1 (despite @pikuler got it fixed even on 4.4 RC)
  - Encountered both from Godot official site and Steam; they are almost the same actually (Steam API libs added)
- Launching Godot via console with --verbose param gave me no info about crashing
### A workaround!!! (not fix)
I tried something extraordinary. Reading [this topic](https://forum.godotengine.org/t/phantom-camera-causes-a-mass-of-errors/71143), I thought about changing rendering mode to the opposite: from Forward+ to Compatibility.

Guess what? No freezing! Finally!

Well, the bad news are that I can't use advanced graphics (e.g. Glow from Environment) in my game that require Forward+ rendering mode.

After some experiments I've found another interesting thing: if I go to Windows settings > Display > Graphics settings > Add exe of Godot and choose my Intel Iris Xe Graphics instead of my videocard, then I can run Godot with Forward+ with no freezing too! _(But with low fps about 30 or less cuz y'know running a 3D game on CPU should look bad)_.

### What about using the other working PC?
I'd like to, however it's not mine + I often work sitting in a cafeteria with my laptop so I certainly want to develop in Godot using my laptop.

Hope all this information may help.

**Comment by 0-Vanes-0** [comment]
After some time I tried to go to Forward+ render mode. I suspect that some recent Nvidia drivers update could have caused fixing this issue. No idea what was that but I'm finally happy.

**Comment by ramokz** [comment]
Thanks again for sharing all the explorations and details.

It sounds like it's a hardware (driver?) specific issue, which is fairly notorious to debug.
I suspect it might also have impacted other parts of Godot, as the addon doesn't do anything magical that isn't natively part of GDScript. Reckon the addon was a symptom rather than the cause, but obviously it's difficult to tell without a lot more testing, which is inherently difficult due to how it occurred in the first place.

As always, feel free to share more findings if anything changes.

**Comment by lord-muad-dib** [comment]
hello, my 2 cents. when i tried setting: project settings->rendering->driver->thread model: to "separate" (which is experimental by the way) i had similar feedback on several plugins when using my discrete nvidia card.
if it still comes up, check if you have that setting and put it back to safe.
might be that might be not, good luck
